export const ROOM_OWNERSHIP_VERIFIER = Symbol("ROOM_OWNERSHIP_VERIFIER");

/**
 * Confirms the acting user actually controls the IMVU room they're binding —
 * mirrors the "VALIDAR SALA" mechanism observed in Vusic: a one-time token is
 * generated by us, the owner pastes it into their room's IMVU description,
 * and this port checks whether it's actually there.
 *
 * IMVU does not publish a documented API for reading a room's description
 * over plain HTTP. Whatever concrete implementation backs this port is
 * therefore OBSERVED/REVERSE-ENGINEERED CLIENT BEHAVIOR, not a documented
 * endpoint — see `imvu-room-page.verifier.ts` for the current status. This
 * interface exists specifically so that implementation detail stays isolated
 * and swappable per the External Integrations Policy.
 */
export interface IRoomOwnershipVerifier {
  descriptionContainsToken(imvuRoomId: string, token: string): Promise<boolean>;
}
