#!/bin/sh
# Regenerates the Liquidsoap script from Arcana's list of currently
# verified + bot-licensed rooms. Run on a loop by entrypoint.sh so newly
# bound rooms get a mountpoint without a full redeploy.
set -eu

OUT_FILE="${1:-/app/radio.liq}"
TMP_FILE=$(mktemp)

{
  echo "# Auto-generated by generate-liquidsoap.sh — do not edit by hand."
  # .set(...) rather than the newer := ref syntax — Debian bookworm (this
  # image's base) ships Liquidsoap 2.1.3, where settings.log.level/etc. are
  # plain getter functions, not refs, and ":=" fails with "this value has
  # type () -> _ but it should be a subtype of ref(_)". .set() is the older
  # form that both 2.1.x and 2.2.x accept (2.2.x just emits a deprecation
  # warning, not an error) — confirmed against a real 2.1.3 failure on Railway.
  echo "settings.log.level.set(3)"
  # The container runs as root (Icecast needs root to bind then drops
  # privileges via <changeowner> in icecast.xml.template; Liquidsoap has no
  # equivalent directive, so it refuses to start at all otherwise — confirmed
  # by running this exact generated script for real, not just --check).
  echo "settings.init.allow_root.set(true)"
  echo ""

  ROOMS_JSON=$(curl -s --max-time 10 -H "x-internal-token: ${STREAMING_INTERNAL_TOKEN}" "${API_URL}/internal/streaming/active-rooms")

  echo "${ROOMS_JSON}" | jq -c '.[]' | while read -r room; do
    ROOM_ID=$(echo "${room}" | jq -r '.roomId')
    STREAM_KEY=$(echo "${room}" | jq -r '.streamKey')
    # Liquidsoap variable names must be valid identifiers — room ids are
    # cuids (already alphanumeric) but sanitize defensively anyway.
    VAR="r_$(echo "${ROOM_ID}" | tr -c 'a-zA-Z0-9' '_')"

    cat <<LIQ
def next_${VAR}() =
  url = string.trim(process.read("/app/next-track.sh ${ROOM_ID}"))
  if url == "" then
    null()
  else
    request.create(url)
  end
end
# retry_delay: without it, request.dynamic defaults to polling next_${VAR}
# (and therefore next-track.sh -> the API) up to 10x/sec — confirmed against
# a real running instance, not just read from docs. 4s keeps API load sane
# per active room while still picking up a freshly queued track quickly.
queue_${VAR} = request.dynamic(retry_delay=4., next_${VAR})
# A room owner's own live mic/DJ broadcast — checked per *connection attempt*
# only (not polled like next_${VAR}), so this never hits the hammering bug
# fixed above. auth calls out to the API on every harbor connect; the
# session password is short-lived and rotates per LiveSession, never reused
# from Icecast's own AutoDJ source password.
def live_auth_${VAR}(login) =
  string.trim(process.read("/app/check-live-auth.sh ${ROOM_ID} " ^ login.password)) == "ok"
end
live_${VAR} = input.harbor("live-${STREAM_KEY}", port=${LIQUIDSOAP_HARBOR_PORT}, auth=live_auth_${VAR})
# fallback to silence instead of dropping the mount when a room has
# nothing uploaded yet (e.g. right after binding, before the first track).
# Live mic/DJ takes priority over AutoDJ whenever it's actually connected.
src_${VAR} = fallback(track_sensitive=false, [live_${VAR}, queue_${VAR}, blank()])
output.icecast(%mp3(bitrate=128),
  host="localhost", port=${ICECAST_PORT},
  password="${ICECAST_SOURCE_PASSWORD}",
  mount="/live/${STREAM_KEY}.mp3",
  src_${VAR})

LIQ
  done
} > "${TMP_FILE}"

mv "${TMP_FILE}" "${OUT_FILE}"
