#!/bin/sh
# Regenerates the Liquidsoap script from Arcana's list of currently
# verified + bot-licensed rooms. Run on a loop by entrypoint.sh so newly
# bound rooms get a mountpoint without a full redeploy.
set -eu

OUT_FILE="${1:-/app/radio.liq}"
TMP_FILE=$(mktemp)

{
  echo "# Auto-generated by generate-liquidsoap.sh — do not edit by hand."
  echo "settings.log.level := 3"
  # The container runs as root (Icecast needs root to bind then drops
  # privileges via <changeowner> in icecast.xml.template; Liquidsoap has no
  # equivalent directive, so it refuses to start at all otherwise — confirmed
  # by running this exact generated script for real, not just --check).
  echo "settings.init.allow_root := true"
  echo ""

  ROOMS_JSON=$(curl -s --max-time 10 -H "x-internal-token: ${STREAMING_INTERNAL_TOKEN}" "${API_URL}/internal/streaming/active-rooms")

  echo "${ROOMS_JSON}" | jq -c '.[]' | while read -r room; do
    ROOM_ID=$(echo "${room}" | jq -r '.roomId')
    STREAM_KEY=$(echo "${room}" | jq -r '.streamKey')
    # Liquidsoap variable names must be valid identifiers — room ids are
    # cuids (already alphanumeric) but sanitize defensively anyway.
    VAR="r_$(echo "${ROOM_ID}" | tr -c 'a-zA-Z0-9' '_')"

    cat <<LIQ
def next_${VAR}() =
  url = string.trim(process.read("/app/next-track.sh ${ROOM_ID}"))
  if url == "" then
    request.create("invalid://no-track-available")
  else
    request.create(url)
  end
end
queue_${VAR} = request.dynamic(next_${VAR})
# fallback to silence instead of dropping the mount when a room has
# nothing uploaded yet (e.g. right after binding, before the first track).
src_${VAR} = fallback(track_sensitive=false, [queue_${VAR}, blank()])
output.icecast(%mp3(bitrate=128),
  host="localhost", port=${ICECAST_PORT},
  password="${ICECAST_SOURCE_PASSWORD}",
  mount="/live/${STREAM_KEY}.mp3",
  src_${VAR})

LIQ
  done
} > "${TMP_FILE}"

mv "${TMP_FILE}" "${OUT_FILE}"
